//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMonk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:37771")]
        public string Bitcoin_DaemonUrl {
            get {
                return ((string)(this["Bitcoin_DaemonUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:37773")]
        public string Bitcoin_DaemonUrl_Testnet {
            get {
                return ((string)(this["Bitcoin_DaemonUrl_Testnet"]));
            }
            set {
                this["Bitcoin_DaemonUrl_Testnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bitcoin_WalletPassword {
            get {
                return ((string)(this["Bitcoin_WalletPassword"]));
            }
            set {
                this["Bitcoin_WalletPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p1")]
        public string Bitcoin_RpcUsername {
            get {
                return ((string)(this["Bitcoin_RpcUsername"]));
            }
            set {
                this["Bitcoin_RpcUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p2")]
        public string Bitcoin_RpcPassword {
            get {
                return ((string)(this["Bitcoin_RpcPassword"]));
            }
            set {
                this["Bitcoin_RpcPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RpcRequestTimeoutInSeconds {
            get {
                return ((int)(this["RpcRequestTimeoutInSeconds"]));
            }
            set {
                this["RpcRequestTimeoutInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtractMyPrivateKeys {
            get {
                return ((bool)(this["ExtractMyPrivateKeys"]));
            }
            set {
                this["ExtractMyPrivateKeys"] = value;
            }
        }
    }
}
